version: '3'

tasks:
  # Update this repo with the copier-template
  # `--vcs-ref HEAD` to avoid `You are downgrading from 0.1.0.post2.dev0+0a9a33e to 0.1.0. Downgrades are not supported.`
  update:
    cmds:
      - |
        copier update --vcs-ref HEAD .
  # Create and run the container
  run:
    cmds:
      - |
        docker run \
          --name site-com-combostrap \
          -d \
          -p 8082:80 \
          --user 1000:1000 \
          -e DOKU_DOCKER_ENV=dev \
          -e DOKU_DOCKER_ACL_POLICY='public' \
          -e DOKU_DOCKER_ADMIN_NAME='admin' \
          -e DOKU_DOCKER_ADMIN_PASSWORD='welcome' \
          -v $PWD:/var/www/html \
          ghcr.io/combostrap/dokuwiki:php8.3-latest
  # Stop the container
  stop:
    cmds:
      - |
        docker stop site-com-combostrap
  # Rm the container
  rm:
    cmds:
      - |
        docker rm site-com-combostrap
  # Start the container
  start:
    cmds:
      - |
        docker start site-com-combostrap
  # Broken links
  broken:
    cmds:
      - |
        # Delete non-existing pages in the database
        docker exec -it site-com-combostrap php ./bin/plugin.php combo sync /
        docker exec -it site-com-combostrap php ./bin/plugin.php combo broken-links
  # Frontmatter
  frontmatter:
    cmds:
      - |
        docker exec -it site-com-combostrap php ./bin/plugin.php combo metadata-to-frontmatter :
