<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Sat, 24 Aug 2024 10:48:15 +0000
 */

$conf['title'] = 'ComboStrap';
$conf['tagline'] = 'Create your footprint that last ForEver. Advertise yourself, your documentation or your company with a product that makes website design, creation and management, unique, easy and fun';
$conf['youarehere'] = 1;
$conf['toptoclevel'] = '2';
$conf['tocminheads'] = '1';
$conf['maxseclevel'] = '4';
$conf['useheading'] = '1';
$conf['hidepages'] = '(headerbar|footerbar|sidekickbar|combostrap|sidebar)';
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register,resendpwd,profile,profile_delete,subscribe,unsubscribe';
$conf['indexdelay'] = 0;
$conf['target']['extern'] = '_blank';
$conf['sitemap'] = 10;
$conf['plugin']['authldap']['attributes'] = array();
$conf['plugin']['combo']['MinimalNamesCountForAutomaticCanonical'] = '1';
$conf['plugin']['combo']['useCanonicalValueForGoogleAnalyticsPageView'] = 1;
$conf['plugin']['combo']['disableDokuwikiStylesheet'] = 1;
$conf['plugin']['combo']['prismTheme'] = 'prism';
$conf['plugin']['combo']['lowQualityPageProtectionEnable'] = 1;
$conf['plugin']['combo']['mandatoryQualityRules'] = 'internal_backlinks_min,internal_links_min,words_min';
$conf['plugin']['combo']['twitterSiteHandle'] = '@combostrapweb';
$conf['plugin']['combo']['twitterSiteId'] = '1283330969332842497';
$conf['plugin']['combo']['pageUrlType'] = 'homed slug';
$conf['plugin']['combo']['enableFrontMatterOnSubmit'] = 1;
$conf['plugin']['combo']['primaryColor'] = '#7611f7';
$conf['plugin']['combo']['privateRailbar'] = 1;
$conf['plugin']['combo']['combo-conf-005'] = 'combo';
$conf['plugin']['googleanalytics']['GTAGID'] = 'UA-171187553-1';
$conf['plugin']['googleanalytics']['dont_count_admin'] = '1';
$conf['plugin']['googleanalytics']['dont_count_users'] = '1';
$conf['plugin']['googleanalytics']['track_links'] = '1';
$conf['plugin']['combo']['pageProtectionMode'] = 'hidden';
