<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: gerardnico
 * Date: Thu, 15 Jul 2021 11:06:37 +0000
 */

$conf['title'] = 'ComboStrap';
$conf['template'] = 'strap';
$conf['tagline'] = 'Create your footprint that last ForEver. Advertise yourself, your documentation or your company with a product that makes website design, creation and management, unique, easy and fun';
$conf['breadcrumbs'] = 10;
$conf['youarehere'] = 1;
$conf['maxseclevel'] = '4';
$conf['useheading'] = '1';
$conf['hidepages'] = '(headerbar|footerbar|sidekickbar|combostrap|sidebar)';
$conf['disableactions'] = 'register,resendpwd,profile,profile_delete,subscribe,unsubscribe';
$conf['indexdelay'] = 0;
$conf['htmlok'] = 1;
$conf['target']['extern'] = '_blank';
$conf['sitemap'] = 10;
$conf['userewrite'] = '1';
$conf['useslash'] = 1;
$conf['renderer_xhtml'] = 'combo_renderer';
$conf['plugin']['authldap']['attributes'] = array();
$conf['plugin']['combo']['MinimalNamesCountForAutomaticCanonical'] = '1';
$conf['plugin']['combo']['disableDokuwikiStylesheet'] = 1;
$conf['plugin']['combo']['prismTheme'] = 'prism';
$conf['plugin']['combo']['lowQualityPageProtectionEnable'] = 1;
$conf['plugin']['combo']['pageProtectionMode'] = 'hidden';
$conf['plugin']['combo']['mandatoryQualityRules'] = 'internal_backlinks_min,internal_links_min,words_min';
$conf['plugin']['combo']['twitterSiteHandle'] = '@combostrapweb';
$conf['plugin']['combo']['twitterSiteId'] = '1283330969332842497';
$conf['plugin']['combo']['outlineNumberingEnable'] = 1;
$conf['plugin']['googleanalytics']['GAID'] = 'UA-171187553-1';
$conf['plugin']['googleanalytics']['dont_count_admin'] = 1;
$conf['plugin']['googleanalytics']['dont_count_users'] = 1;
$conf['plugin']['googleanalytics']['track_links'] = 1;
$conf['tpl']['strap']['footerSlotPageName'] = 'slot_footer';
$conf['tpl']['strap']['headerSlotPageName'] = 'slot_header';
$conf['tpl']['strap']['sidekickSlotPageName'] = 'slot_sidekick';
$conf['tpl']['strap']['heightFixedTopMenuBar'] = '56';
$conf['tpl']['strap']['privateRailbar'] = 1;
